# Identação aqui é super importante
version: '3.7'

# Uma lista de serviços

services:
  
  # Vou ter um serviço que estou apelidando dentro do compose de api-pass-in ou qualquer outra coisa. Que nesse caso é a imagem que criamos
  api-pass-in:
    # Faz um bild
    build:
      # Passamos o nosso dockerfile que esta nessa raiz do mesmo arquivo do docker-compose, que é o dockerfile. Caso esteja em outro lugar so passar o diretorio corretamente em vez do .
      context: .
      # Caso o seu docker file tenha outro nome
      # Dockerfile:
    # Se quiser pode passar outro nome aqui
    container_name: api_pass_in
    # Porta definida na nossa imagem
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=development